FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
 && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project


COPY front-end/ front-end/

EXPOSE 8501

CMD ["uv", "run", "streamlit", "run", "frontend/main.py", "--server.address=0.0.0.0", "--server.port=8501"]

